export const USER_API_END_POINT = "http://localhost:8000/api/v1/user";
export const JOB_API_END_POINT = "http://localhost:8000/api/v1/job";
export const APPLICATION_API_END_POINT =
  "http://localhost:8000/api/v1/application";
export const COMPANY_API_END_POINT = "http://localhost:8000/api/v1/company";

export const defaultJobData = [
  {
    _id: "job011",
    title: "Full Stack Developer",
    description:
      "Develop and manage both frontend and backend services using JavaScript and Python.",
    requirements: ["JavaScript", "Python", "React", "Django", "SQL"],
    salary: 78000,
    location: "Los Angeles, CA",
    jobType: "Full-time",
    experienceLevel: "Mid-level",
    position: "Developer",
    company: "Tesla",
    created_by: "User133",
  },
  {
    _id: "job012",
    title: "Cloud Engineer",
    description:
      "Design and implement scalable cloud infrastructures using AWS and Terraform.",
    requirements: ["AWS", "Terraform", "Cloud Security", "Automation"],
    salary: 92000,
    location: "Miami, FL",
    jobType: "Full-time",
    experienceLevel: "Senior",
    position: "Engineer",
    company: "Netflix",
    created_by: "User134",
  },
  {
    _id: "job013",
    title: "Graphic Designer",
    description:
      "Create compelling graphics and visuals for digital and print media.",
    requirements: [
      "Adobe Photoshop",
      "Illustrator",
      "InDesign",
      "Creative Suite",
    ],
    salary: 55000,
    location: "Portland, OR",
    jobType: "Part-time",
    experienceLevel: "Junior",
    position: "Designer",
    company: "Nike",
    created_by: "User135",
  },
  {
    _id: "job014",
    title: "Data Scientist",
    description:
      "Develop data models to extract actionable insights from large datasets.",
    requirements: [
      "Python",
      "R",
      "Machine Learning",
      "Data Visualization",
      "SQL",
    ],
    salary: 88000,
    location: "Dallas, TX",
    jobType: "Full-time",
    experienceLevel: "Mid-level",
    position: "Scientist",
    company: "Uber",
    created_by: "User136",
  },
  {
    _id: "job015",
    title: "AI Engineer",
    description:
      "Design and implement AI models and algorithms for real-world applications.",
    requirements: [
      "Python",
      "PyTorch",
      "Natural Language Processing",
      "Computer Vision",
    ],
    salary: 100000,
    location: "Remote",
    jobType: "Full-time",
    experienceLevel: "Senior",
    position: "Engineer",
    company: "Spotify",
    created_by: "User137",
  },
  {
    _id: "job016",
    title: "Infrastructure Engineer",
    description:
      "Develop and maintain infrastructure solutions to support application scalability.",
    requirements: ["Linux", "Ansible", "Docker", "Kubernetes", "CI/CD"],
    salary: 87000,
    location: "Atlanta, GA",
    jobType: "Full-time",
    experienceLevel: "Mid-level",
    position: "Engineer",
    company: "Red Hat",
    created_by: "User138",
  },
  {
    _id: "job017",
    title: "Mobile Developer",
    description: "Create and optimize mobile apps using Swift and Kotlin.",
    requirements: ["Swift", "Kotlin", "iOS", "Android", "Mobile Development"],
    salary: 72000,
    location: "Remote",
    jobType: "Contract",
    experienceLevel: "Mid-level",
    position: "Developer",
    company: "Square",
    created_by: "User139",
  },
  {
    _id: "job018",
    title: "Product Designer",
    description:
      "Lead design efforts for new products, from ideation to user testing.",
    requirements: ["Figma", "User Research", "Wireframing", "Prototyping"],
    salary: 96000,
    location: "New York, NY",
    jobType: "Full-time",
    experienceLevel: "Senior",
    position: "Designer",
    company: "Adobe",
    created_by: "User140",
  },
  {
    _id: "job019",
    title: "IT Security Specialist",
    description:
      "Ensure the security of company systems through proactive monitoring and risk assessments.",
    requirements: [
      "Network Security",
      "Firewall Management",
      "Incident Response",
      "SIEM",
    ],
    salary: 83000,
    location: "Chicago, IL",
    jobType: "Full-time",
    experienceLevel: "Mid-level",
    position: "Specialist",
    company: "Intel",
    created_by: "User141",
  },
  {
    _id: "job020",
    title: "Technical Lead",
    description:
      "Oversee technical decisions and development processes for software projects.",
    requirements: [
      "Leadership",
      "Agile Methodologies",
      "Cloud Platforms",
      "Microservices",
    ],
    salary: 125000,
    location: "San Jose, CA",
    jobType: "Full-time",
    experienceLevel: "Senior",
    position: "Lead",
    company: "Google",
    created_by: "User142",
  },
];
